# Created by kash
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS

# History substring search
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Editor
export EDITOR=nvim
export VISUAL=nvim

# Path
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$PATH:/opt/windscribe"
export PATH="$HOME/.local/bin:$PATH"

# Qt
export QT_QPA_PLATFORMTHEME=qt6ct
export XDG_MENU_PREFIX=arch-

# Aliases - configs
alias hyprconf="nvim ~/.config/hypr/hyprland.conf"
alias fetchconf="nvim ~/.config/fastfetch/config.jsonc"
alias zshconf="nvim ~/.zshrc"

# Aliases - caelestia (remove after switching)
alias caeconf="nvim ~/.config/caelestia/shell.json"
alias caefiles="cd ~/.config/quickshell/caelestia"

# Aliases - utils
alias unmount='udisksctl unmount -b /dev/sda1 && udisksctl power-off -b /dev/sda'
alias matrix="unimatrix -c cyan -s 93 -f -l kkns -a"
alias matrixb="cmatrix -C blue -u 7"
alias matrixc="cmatrix -C cyan -u 8 -s"

# Functions
ytmp3() {
  if [[ $# -eq 2 ]]; then
    yt-dlp -x --audio-format mp3 --audio-quality 0 --embed-thumbnail --embed-metadata \
      -P "/home/kashmira/Songs/New" \
      -o "${1}.%(ext)s" \
      --postprocessor-args "ffmpeg:-metadata title=\"${1}\"" \
      "${2}"
  else
    yt-dlp -x --audio-format mp3 --audio-quality 0 --embed-thumbnail --embed-metadata \
      -P "/home/kashmira/Songs/New" \
      -o "%(title)s.%(ext)s" \
      "${1}"
  fi
}

function cheat() { curl "cheat.sh/$1" }

# fzf
eval "$(fzf --zsh)"

# eza (ls replacement)
alias ls="eza --icons=always"
alias ll="eza -lh --icons=always --git"
alias la="eza -lah --icons=always --git"
alias lt="eza --tree --icons=always --level=2"

# zoxide
eval "$(zoxide init zsh)"

# Prompt
eval "$(starship init zsh)"

# Caelestia (remove after switching)
cat ~/.local/state/caelestia/sequences.txt 2>/dev/null

fastfetch
